// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_status_page_component

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func StatusPageComponentResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"display_metrics": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Show this component's response time metrics on the status page.",
				MarkdownDescription: "Show this component's response time metrics on the status page.",
				Default:             booldefault.StaticBool(true),
			},
			"display_uptime": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Show this component's uptime and historical incidents on the status page.",
				MarkdownDescription: "Show this component's uptime and historical incidents on the status page.",
				Default:             booldefault.StaticBool(true),
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Status Page Component ID",
				MarkdownDescription: "Status Page Component ID",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(8),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "a name for the component",
				MarkdownDescription: "a name for the component",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"status": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Status of the component",
				MarkdownDescription: "Status of the component",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"OPERATIONAL",
						"MAJOR_OUTAGE",
						"PARTIAL_OUTAGE",
						"DEGRADED_PERFORMANCE",
						"NO_IMPACT",
						"MAINTENANCE",
					),
				},
				Default: stringdefault.StaticString("OPERATIONAL"),
			},
			"status_page_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Status Page ID",
				MarkdownDescription: "Status Page ID",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(8),
				},
			},
		},
	}
}

type StatusPageComponentModel struct {
	DisplayMetrics types.Bool   `tfsdk:"display_metrics"`
	DisplayUptime  types.Bool   `tfsdk:"display_uptime"`
	Id             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	Status         types.String `tfsdk:"status"`
	StatusPageId   types.String `tfsdk:"status_page_id"`
}
