// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_webhook

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func WebhookResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"check_ids": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "IDs of uptime checks to associate with this webhook",
				MarkdownDescription: "IDs of uptime checks to associate with this webhook",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Optional description of the webhook",
				MarkdownDescription: "Optional description of the webhook",
			},
			"events": schema.ListAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "Event types this webhook should subscribe to",
				MarkdownDescription: "Event types this webhook should subscribe to",
				Validators: []validator.List{
					listvalidator.SizeAtLeast(1),
				},
			},
			"heartbeat_ids": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "IDs of heartbeats to associate with this webhook",
				MarkdownDescription: "IDs of heartbeats to associate with this webhook",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Webhook ID",
				MarkdownDescription: "Webhook ID",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(8),
				},
			},
			"status_page_ids": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "IDs of status pages to associate with this webhook",
				MarkdownDescription: "IDs of status pages to associate with this webhook",
			},
			"url": schema.StringAttribute{
				Required:            true,
				Description:         "Webhook endpoint URL",
				MarkdownDescription: "Webhook endpoint URL",
			},
		},
	}
}

type WebhookModel struct {
	CheckIds      types.List   `tfsdk:"check_ids"`
	Description   types.String `tfsdk:"description"`
	Events        types.List   `tfsdk:"events"`
	HeartbeatIds  types.List   `tfsdk:"heartbeat_ids"`
	Id            types.String `tfsdk:"id"`
	StatusPageIds types.List   `tfsdk:"status_page_ids"`
	Url           types.String `tfsdk:"url"`
}
