// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_status_page_scheduled_maintenance

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func StatusPageScheduledMaintenanceResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"components_affected": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Component IDs affected by this maintenance",
				MarkdownDescription: "Component IDs affected by this maintenance",
			},
			"description": schema.StringAttribute{
				Required:            true,
				Description:         "Description of the scheduled maintenance",
				MarkdownDescription: "Description of the scheduled maintenance",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"duration_minutes": schema.Int64Attribute{
				Required:            true,
				Description:         "How long (in minutes) the maintenance is expected to last",
				MarkdownDescription: "How long (in minutes) the maintenance is expected to last",
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Scheduled Maintenance ID",
				MarkdownDescription: "Scheduled Maintenance ID",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(8),
				},
			},
			"notifications": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"an_hour_before": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Notify subscribers one hour before maintenance starts",
						MarkdownDescription: "Notify subscribers one hour before maintenance starts",
						Default:             booldefault.StaticBool(false),
					},
					"at_end": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Notify subscribers when maintenance ends",
						MarkdownDescription: "Notify subscribers when maintenance ends",
						Default:             booldefault.StaticBool(true),
					},
					"at_start": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Notify subscribers when maintenance starts",
						MarkdownDescription: "Notify subscribers when maintenance starts",
						Default:             booldefault.StaticBool(true),
					},
				},
				CustomType: NotificationsType{
					ObjectType: types.ObjectType{
						AttrTypes: NotificationsValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Notification settings for subscribers",
				MarkdownDescription: "Notification settings for subscribers",
			},
			"start_date": schema.StringAttribute{
				Required:            true,
				Description:         "When the scheduled maintenance is expected to start (ISO 8601)",
				MarkdownDescription: "When the scheduled maintenance is expected to start (ISO 8601)",
			},
			"status_page_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Status Page ID",
				MarkdownDescription: "Status Page ID",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(8),
				},
			},
			"title": schema.StringAttribute{
				Required:            true,
				Description:         "Title of the scheduled maintenance",
				MarkdownDescription: "Title of the scheduled maintenance",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
		},
	}
}

type StatusPageScheduledMaintenanceModel struct {
	ComponentsAffected types.List         `tfsdk:"components_affected"`
	Description        types.String       `tfsdk:"description"`
	DurationMinutes    types.Int64        `tfsdk:"duration_minutes"`
	Id                 types.String       `tfsdk:"id"`
	Notifications      NotificationsValue `tfsdk:"notifications"`
	StartDate          types.String       `tfsdk:"start_date"`
	StatusPageId       types.String       `tfsdk:"status_page_id"`
	Title              types.String       `tfsdk:"title"`
}

var _ basetypes.ObjectTypable = NotificationsType{}

type NotificationsType struct {
	basetypes.ObjectType
}

func (t NotificationsType) Equal(o attr.Type) bool {
	other, ok := o.(NotificationsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t NotificationsType) String() string {
	return "NotificationsType"
}

func (t NotificationsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	anHourBeforeAttribute, ok := attributes["an_hour_before"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`an_hour_before is missing from object`)

		return nil, diags
	}

	anHourBeforeVal, ok := anHourBeforeAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`an_hour_before expected to be basetypes.BoolValue, was: %T`, anHourBeforeAttribute))
	}

	atEndAttribute, ok := attributes["at_end"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`at_end is missing from object`)

		return nil, diags
	}

	atEndVal, ok := atEndAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`at_end expected to be basetypes.BoolValue, was: %T`, atEndAttribute))
	}

	atStartAttribute, ok := attributes["at_start"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`at_start is missing from object`)

		return nil, diags
	}

	atStartVal, ok := atStartAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`at_start expected to be basetypes.BoolValue, was: %T`, atStartAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return NotificationsValue{
		AnHourBefore: anHourBeforeVal,
		AtEnd:        atEndVal,
		AtStart:      atStartVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewNotificationsValueNull() NotificationsValue {
	return NotificationsValue{
		state: attr.ValueStateNull,
	}
}

func NewNotificationsValueUnknown() NotificationsValue {
	return NotificationsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewNotificationsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (NotificationsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing NotificationsValue Attribute Value",
				"While creating a NotificationsValue value, a missing attribute value was detected. "+
					"A NotificationsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NotificationsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid NotificationsValue Attribute Type",
				"While creating a NotificationsValue value, an invalid attribute value was detected. "+
					"A NotificationsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NotificationsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("NotificationsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra NotificationsValue Attribute Value",
				"While creating a NotificationsValue value, an extra attribute value was detected. "+
					"A NotificationsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra NotificationsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewNotificationsValueUnknown(), diags
	}

	anHourBeforeAttribute, ok := attributes["an_hour_before"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`an_hour_before is missing from object`)

		return NewNotificationsValueUnknown(), diags
	}

	anHourBeforeVal, ok := anHourBeforeAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`an_hour_before expected to be basetypes.BoolValue, was: %T`, anHourBeforeAttribute))
	}

	atEndAttribute, ok := attributes["at_end"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`at_end is missing from object`)

		return NewNotificationsValueUnknown(), diags
	}

	atEndVal, ok := atEndAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`at_end expected to be basetypes.BoolValue, was: %T`, atEndAttribute))
	}

	atStartAttribute, ok := attributes["at_start"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`at_start is missing from object`)

		return NewNotificationsValueUnknown(), diags
	}

	atStartVal, ok := atStartAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`at_start expected to be basetypes.BoolValue, was: %T`, atStartAttribute))
	}

	if diags.HasError() {
		return NewNotificationsValueUnknown(), diags
	}

	return NotificationsValue{
		AnHourBefore: anHourBeforeVal,
		AtEnd:        atEndVal,
		AtStart:      atStartVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewNotificationsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) NotificationsValue {
	object, diags := NewNotificationsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewNotificationsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t NotificationsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewNotificationsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewNotificationsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewNotificationsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewNotificationsValueMust(NotificationsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t NotificationsType) ValueType(ctx context.Context) attr.Value {
	return NotificationsValue{}
}

var _ basetypes.ObjectValuable = NotificationsValue{}

type NotificationsValue struct {
	AnHourBefore basetypes.BoolValue `tfsdk:"an_hour_before"`
	AtEnd        basetypes.BoolValue `tfsdk:"at_end"`
	AtStart      basetypes.BoolValue `tfsdk:"at_start"`
	state        attr.ValueState
}

func (v NotificationsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["an_hour_before"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["at_end"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["at_start"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.AnHourBefore.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["an_hour_before"] = val

		val, err = v.AtEnd.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["at_end"] = val

		val, err = v.AtStart.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["at_start"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v NotificationsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v NotificationsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v NotificationsValue) String() string {
	return "NotificationsValue"
}

func (v NotificationsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"an_hour_before": basetypes.BoolType{},
		"at_end":         basetypes.BoolType{},
		"at_start":       basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"an_hour_before": v.AnHourBefore,
			"at_end":         v.AtEnd,
			"at_start":       v.AtStart,
		})

	return objVal, diags
}

func (v NotificationsValue) Equal(o attr.Value) bool {
	other, ok := o.(NotificationsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AnHourBefore.Equal(other.AnHourBefore) {
		return false
	}

	if !v.AtEnd.Equal(other.AtEnd) {
		return false
	}

	if !v.AtStart.Equal(other.AtStart) {
		return false
	}

	return true
}

func (v NotificationsValue) Type(ctx context.Context) attr.Type {
	return NotificationsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v NotificationsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"an_hour_before": basetypes.BoolType{},
		"at_end":         basetypes.BoolType{},
		"at_start":       basetypes.BoolType{},
	}
}
