// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_check

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CheckResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"alert_priority": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Alert Priority",
				MarkdownDescription: "Alert Priority",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"LOW",
						"HIGH",
					),
				},
				Default: stringdefault.StaticString("LOW"),
			},
			"assertions": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"comparison": schema.StringAttribute{
							Required:            true,
							Description:         "Comparison operator",
							MarkdownDescription: "Comparison operator",
							Validators: []validator.String{
								stringvalidator.OneOf(
									"EQUALS",
									"NOT_EQUALS",
									"GREATER_THAN",
									"LESS_THAN",
									"NULL",
									"NOT_NULL",
									"EMPTY",
									"NOT_EMPTY",
									"CONTAINS",
									"NOT_CONTAINS",
									"FALSE",
									"TRUE",
								),
							},
						},
						"expected": schema.StringAttribute{
							Required:            true,
							Description:         "Expected value",
							MarkdownDescription: "Expected value",
						},
						"property": schema.StringAttribute{
							Required:            true,
							Description:         "Property to assert on (JSONPath for JSON_BODY, header name for RESPONSE_HEADERS)",
							MarkdownDescription: "Property to assert on (JSONPath for JSON_BODY, header name for RESPONSE_HEADERS)",
						},
						"type": schema.StringAttribute{
							Required:            true,
							Description:         "Type of assertion",
							MarkdownDescription: "Type of assertion",
							Validators: []validator.String{
								stringvalidator.OneOf(
									"JSON_BODY",
									"TEXT_BODY",
									"RESPONSE_HEADERS",
									"HTML_BODY",
								),
							},
						},
					},
					CustomType: AssertionsType{
						ObjectType: types.ObjectType{
							AttrTypes: AssertionsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Assertions to run on the response",
				MarkdownDescription: "Assertions to run on the response",
			},
			"auth_password": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Password to use for URLs behind HTTP Basic Auth",
				MarkdownDescription: "Password to use for URLs behind HTTP Basic Auth",
			},
			"auth_username": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Username to use for URLs behind HTTP Basic Auth",
				MarkdownDescription: "Username to use for URLs behind HTTP Basic Auth",
			},
			"body": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"confirmation_period_seconds": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Confirmation period in seconds",
				MarkdownDescription: "Confirmation period in seconds",
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
				Default: int64default.StaticInt64(60),
			},
			"discord_alerts": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"follow_redirects": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether to follow redirects",
				MarkdownDescription: "Whether to follow redirects",
				Default:             booldefault.StaticBool(true),
			},
			"headers": schema.MapAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Headers to send with the request",
				MarkdownDescription: "Headers to send with the request",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Uptime Check ID",
				MarkdownDescription: "Uptime Check ID",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(8),
				},
			},
			"incident_io_alerts": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"method": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "HTTP Method",
				MarkdownDescription: "HTTP Method",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"GET",
						"HEAD",
						"POST",
						"PUT",
						"PATCH",
						"DELETE",
					),
				},
				Default: stringdefault.StaticString("GET"),
			},
			"microsoft_teams_alerts": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the check",
				MarkdownDescription: "Name of the check",
			},
			"oncall_alerts": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "IDs of on-call integrations (Grafana, PagerDuty, Opsgenie, Spike)",
				MarkdownDescription: "IDs of on-call integrations (Grafana, PagerDuty, Opsgenie, Spike)",
			},
			"recovery_period_seconds": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Recovery period in seconds",
				MarkdownDescription: "Recovery period in seconds",
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
				Default: int64default.StaticInt64(180),
			},
			"reminder_alert_interval_minutes": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Interval in minutes between reminders (-1 for never)",
				MarkdownDescription: "Interval in minutes between reminders (-1 for never)",
				Validators: []validator.Int64{
					int64validator.AtLeast(-1),
				},
				Default: int64default.StaticInt64(1440),
			},
			"slack_alerts": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"test_interval": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Interval in seconds between checks",
				MarkdownDescription: "Interval in seconds between checks",
				Validators: []validator.Int64{
					int64validator.AtLeast(30),
				},
			},
			"test_regions": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"text_to_search_for": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Text to search for in the response",
				MarkdownDescription: "Text to search for in the response",
			},
			"timeout": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Timeout in milliseconds",
				MarkdownDescription: "Timeout in milliseconds",
				Validators: []validator.Int64{
					int64validator.AtLeast(1000),
				},
				Default: int64default.StaticInt64(10000),
			},
			"type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Type of check",
				MarkdownDescription: "Type of check",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"UPTIME_CHECK",
						"BROWSER_CHECK",
					),
				},
				Default: stringdefault.StaticString("UPTIME_CHECK"),
			},
			"url": schema.StringAttribute{
				Required:            true,
				Description:         "URL to check",
				MarkdownDescription: "URL to check",
			},
			"user_alerts": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"verify_ssl": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether to fail a check if SSL verification fails",
				MarkdownDescription: "Whether to fail a check if SSL verification fails",
				Default:             booldefault.StaticBool(false),
			},
			"version": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Version of the Browser Check",
				MarkdownDescription: "Version of the Browser Check",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"NODE20_PLAYWRIGHT",
					),
				},
			},
			"webhook_alerts": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "IDs of webhooks to associate with this check",
				MarkdownDescription: "IDs of webhooks to associate with this check",
			},
		},
	}
}

type CheckModel struct {
	AlertPriority                types.String `tfsdk:"alert_priority"`
	Assertions                   types.List   `tfsdk:"assertions"`
	AuthPassword                 types.String `tfsdk:"auth_password"`
	AuthUsername                 types.String `tfsdk:"auth_username"`
	Body                         types.String `tfsdk:"body"`
	ConfirmationPeriodSeconds    types.Int64  `tfsdk:"confirmation_period_seconds"`
	DiscordAlerts                types.List   `tfsdk:"discord_alerts"`
	FollowRedirects              types.Bool   `tfsdk:"follow_redirects"`
	Headers                      types.Map    `tfsdk:"headers"`
	Id                           types.String `tfsdk:"id"`
	IncidentIoAlerts             types.List   `tfsdk:"incident_io_alerts"`
	Method                       types.String `tfsdk:"method"`
	MicrosoftTeamsAlerts         types.List   `tfsdk:"microsoft_teams_alerts"`
	Name                         types.String `tfsdk:"name"`
	OncallAlerts                 types.List   `tfsdk:"oncall_alerts"`
	RecoveryPeriodSeconds        types.Int64  `tfsdk:"recovery_period_seconds"`
	ReminderAlertIntervalMinutes types.Int64  `tfsdk:"reminder_alert_interval_minutes"`
	SlackAlerts                  types.List   `tfsdk:"slack_alerts"`
	TestInterval                 types.Int64  `tfsdk:"test_interval"`
	TestRegions                  types.List   `tfsdk:"test_regions"`
	TextToSearchFor              types.String `tfsdk:"text_to_search_for"`
	Timeout                      types.Int64  `tfsdk:"timeout"`
	Type                         types.String `tfsdk:"type"`
	Url                          types.String `tfsdk:"url"`
	UserAlerts                   types.List   `tfsdk:"user_alerts"`
	VerifySsl                    types.Bool   `tfsdk:"verify_ssl"`
	Version                      types.String `tfsdk:"version"`
	WebhookAlerts                types.List   `tfsdk:"webhook_alerts"`
}

var _ basetypes.ObjectTypable = AssertionsType{}

type AssertionsType struct {
	basetypes.ObjectType
}

func (t AssertionsType) Equal(o attr.Type) bool {
	other, ok := o.(AssertionsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AssertionsType) String() string {
	return "AssertionsType"
}

func (t AssertionsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	comparisonAttribute, ok := attributes["comparison"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`comparison is missing from object`)

		return nil, diags
	}

	comparisonVal, ok := comparisonAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`comparison expected to be basetypes.StringValue, was: %T`, comparisonAttribute))
	}

	expectedAttribute, ok := attributes["expected"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`expected is missing from object`)

		return nil, diags
	}

	expectedVal, ok := expectedAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`expected expected to be basetypes.StringValue, was: %T`, expectedAttribute))
	}

	propertyAttribute, ok := attributes["property"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`property is missing from object`)

		return nil, diags
	}

	propertyVal, ok := propertyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`property expected to be basetypes.StringValue, was: %T`, propertyAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AssertionsValue{
		Comparison:     comparisonVal,
		Expected:       expectedVal,
		Property:       propertyVal,
		AssertionsType: typeVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewAssertionsValueNull() AssertionsValue {
	return AssertionsValue{
		state: attr.ValueStateNull,
	}
}

func NewAssertionsValueUnknown() AssertionsValue {
	return AssertionsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAssertionsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AssertionsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AssertionsValue Attribute Value",
				"While creating a AssertionsValue value, a missing attribute value was detected. "+
					"A AssertionsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AssertionsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AssertionsValue Attribute Type",
				"While creating a AssertionsValue value, an invalid attribute value was detected. "+
					"A AssertionsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AssertionsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AssertionsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AssertionsValue Attribute Value",
				"While creating a AssertionsValue value, an extra attribute value was detected. "+
					"A AssertionsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AssertionsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAssertionsValueUnknown(), diags
	}

	comparisonAttribute, ok := attributes["comparison"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`comparison is missing from object`)

		return NewAssertionsValueUnknown(), diags
	}

	comparisonVal, ok := comparisonAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`comparison expected to be basetypes.StringValue, was: %T`, comparisonAttribute))
	}

	expectedAttribute, ok := attributes["expected"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`expected is missing from object`)

		return NewAssertionsValueUnknown(), diags
	}

	expectedVal, ok := expectedAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`expected expected to be basetypes.StringValue, was: %T`, expectedAttribute))
	}

	propertyAttribute, ok := attributes["property"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`property is missing from object`)

		return NewAssertionsValueUnknown(), diags
	}

	propertyVal, ok := propertyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`property expected to be basetypes.StringValue, was: %T`, propertyAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewAssertionsValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewAssertionsValueUnknown(), diags
	}

	return AssertionsValue{
		Comparison:     comparisonVal,
		Expected:       expectedVal,
		Property:       propertyVal,
		AssertionsType: typeVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewAssertionsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AssertionsValue {
	object, diags := NewAssertionsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAssertionsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AssertionsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAssertionsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAssertionsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAssertionsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAssertionsValueMust(AssertionsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AssertionsType) ValueType(ctx context.Context) attr.Value {
	return AssertionsValue{}
}

var _ basetypes.ObjectValuable = AssertionsValue{}

type AssertionsValue struct {
	Comparison     basetypes.StringValue `tfsdk:"comparison"`
	Expected       basetypes.StringValue `tfsdk:"expected"`
	Property       basetypes.StringValue `tfsdk:"property"`
	AssertionsType basetypes.StringValue `tfsdk:"type"`
	state          attr.ValueState
}

func (v AssertionsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["comparison"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["expected"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["property"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.Comparison.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["comparison"] = val

		val, err = v.Expected.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["expected"] = val

		val, err = v.Property.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["property"] = val

		val, err = v.AssertionsType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AssertionsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AssertionsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AssertionsValue) String() string {
	return "AssertionsValue"
}

func (v AssertionsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"comparison": basetypes.StringType{},
		"expected":   basetypes.StringType{},
		"property":   basetypes.StringType{},
		"type":       basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"comparison": v.Comparison,
			"expected":   v.Expected,
			"property":   v.Property,
			"type":       v.AssertionsType,
		})

	return objVal, diags
}

func (v AssertionsValue) Equal(o attr.Value) bool {
	other, ok := o.(AssertionsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Comparison.Equal(other.Comparison) {
		return false
	}

	if !v.Expected.Equal(other.Expected) {
		return false
	}

	if !v.Property.Equal(other.Property) {
		return false
	}

	if !v.AssertionsType.Equal(other.AssertionsType) {
		return false
	}

	return true
}

func (v AssertionsValue) Type(ctx context.Context) attr.Type {
	return AssertionsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AssertionsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"comparison": basetypes.StringType{},
		"expected":   basetypes.StringType{},
		"property":   basetypes.StringType{},
		"type":       basetypes.StringType{},
	}
}
