// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_status_page

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func StatusPageResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allowed_ips": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "List of IP addresses or CIDR ranges allowed to access this status page",
				MarkdownDescription: "List of IP addresses or CIDR ranges allowed to access this status page",
			},
			"custom_domain": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The custom domain your status page is hosted at.",
				MarkdownDescription: "The custom domain your status page is hosted at.",
			},
			"dark_logo": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Image file contents as a base64 data URL, not a hosted URL. Supports PNG, JPEG, GIF, WebP, SVG and ICO; maximum decoded file size 10 MB. Omit to preserve the image; send null to remove it.",
				MarkdownDescription: "Image file contents as a base64 data URL, not a hosted URL. Supports PNG, JPEG, GIF, WebP, SVG and ICO; maximum decoded file size 10 MB. Omit to preserve the image; send null to remove it.",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(13333436),
				},
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"favicon": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Image file contents as a base64 data URL, not a hosted URL. Supports PNG, JPEG, GIF, WebP, SVG and ICO; maximum decoded file size 10 MB. Omit to preserve the image; send null to remove it.",
				MarkdownDescription: "Image file contents as a base64 data URL, not a hosted URL. Supports PNG, JPEG, GIF, WebP, SVG and ICO; maximum decoded file size 10 MB. Omit to preserve the image; send null to remove it.",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(13333436),
				},
			},
			"hide_from_search_engines": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether to hide the status page from search engines",
				MarkdownDescription: "Whether to hide the status page from search engines",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Status Page ID",
				MarkdownDescription: "Status Page ID",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(8),
				},
			},
			"logo": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Image file contents as a base64 data URL, not a hosted URL. Supports PNG, JPEG, GIF, WebP, SVG and ICO; maximum decoded file size 10 MB. Omit to preserve the image; send null to remove it.",
				MarkdownDescription: "Image file contents as a base64 data URL, not a hosted URL. Supports PNG, JPEG, GIF, WebP, SVG and ICO; maximum decoded file size 10 MB. Omit to preserve the image; send null to remove it.",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(13333436),
				},
			},
			"name": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 100),
				},
			},
			"password": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Password protection. Send null or an empty string to remove it; omit to leave it unchanged.",
				MarkdownDescription: "Password protection. Send null or an empty string to remove it; omit to leave it unchanged.",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(4096),
				},
			},
			"subdomain": schema.StringAttribute{
				Required:            true,
				Description:         "The subdomain your status page will be hosted at. For example \"status\" would become \"status.onlineornot.com\"",
				MarkdownDescription: "The subdomain your status page will be hosted at. For example \"status\" would become \"status.onlineornot.com\"",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^\\w(?:[\\w-]{0,61}\\w)?$"), ""),
				},
			},
		},
	}
}

type StatusPageModel struct {
	AllowedIps            types.List   `tfsdk:"allowed_ips"`
	CustomDomain          types.String `tfsdk:"custom_domain"`
	DarkLogo              types.String `tfsdk:"dark_logo"`
	Description           types.String `tfsdk:"description"`
	Favicon               types.String `tfsdk:"favicon"`
	HideFromSearchEngines types.Bool   `tfsdk:"hide_from_search_engines"`
	Id                    types.String `tfsdk:"id"`
	Logo                  types.String `tfsdk:"logo"`
	Name                  types.String `tfsdk:"name"`
	Password              types.String `tfsdk:"password"`
	Subdomain             types.String `tfsdk:"subdomain"`
}
