// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_status_page

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func StatusPageResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allowed_ips": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "List of IP addresses or CIDR ranges allowed to access this status page",
				MarkdownDescription: "List of IP addresses or CIDR ranges allowed to access this status page",
			},
			"custom_domain": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The custom domain your status page is hosted at.",
				MarkdownDescription: "The custom domain your status page is hosted at.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A description of your status page",
				MarkdownDescription: "A description of your status page",
			},
			"hide_from_search_engines": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether to hide the status page from search engines",
				MarkdownDescription: "Whether to hide the status page from search engines",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Status Page ID",
				MarkdownDescription: "Status Page ID",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(8),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the Status Page",
				MarkdownDescription: "Name of the Status Page",
			},
			"password": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The password required to view your status page. If omitted, keeps existing password. If null or empty string, removes password protection. If non-empty string, sets new password.",
				MarkdownDescription: "The password required to view your status page. If omitted, keeps existing password. If null or empty string, removes password protection. If non-empty string, sets new password.",
			},
			"subdomain": schema.StringAttribute{
				Required:            true,
				Description:         "The subdomain your status page will be hosted at. For example \"status\" would become \"status.onlineornot.com\"",
				MarkdownDescription: "The subdomain your status page will be hosted at. For example \"status\" would become \"status.onlineornot.com\"",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^\\w(?:[\\w-]{0,61}\\w)?$"), ""),
				},
			},
		},
	}
}

type StatusPageModel struct {
	AllowedIps            types.List   `tfsdk:"allowed_ips"`
	CustomDomain          types.String `tfsdk:"custom_domain"`
	Description           types.String `tfsdk:"description"`
	HideFromSearchEngines types.Bool   `tfsdk:"hide_from_search_engines"`
	Id                    types.String `tfsdk:"id"`
	Name                  types.String `tfsdk:"name"`
	Password              types.String `tfsdk:"password"`
	Subdomain             types.String `tfsdk:"subdomain"`
}
