// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_status_page_component_group

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func StatusPageComponentGroupResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Description of the component group",
				MarkdownDescription: "Description of the component group",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Status Page Component Group ID",
				MarkdownDescription: "Status Page Component Group ID",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(8),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the component group",
				MarkdownDescription: "Name of the component group",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"status_page_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Status Page ID",
				MarkdownDescription: "Status Page ID",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(8),
				},
			},
		},
	}
}

type StatusPageComponentGroupModel struct {
	Description  types.String `tfsdk:"description"`
	Id           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	StatusPageId types.String `tfsdk:"status_page_id"`
}
