// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_heartbeat

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func HeartbeatResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"alert_priority": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Alert priority level",
				MarkdownDescription: "Alert priority level",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"LOW",
						"HIGH",
					),
				},
				Default: stringdefault.StaticString("LOW"),
			},
			"discord_alerts": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Array of Discord integration IDs to alert",
				MarkdownDescription: "Array of Discord integration IDs to alert",
			},
			"grace_period": schema.Int64Attribute{
				Required:            true,
				Description:         "Grace period in seconds to wait after missed heartbeat before alerting",
				MarkdownDescription: "Grace period in seconds to wait after missed heartbeat before alerting",
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Heartbeat ID",
				MarkdownDescription: "Heartbeat ID",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(8),
				},
			},
			"incident_io_alerts": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Array of incident.io integration IDs to alert",
				MarkdownDescription: "Array of incident.io integration IDs to alert",
			},
			"microsoft_teams_alerts": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Array of Microsoft Teams integration IDs to alert",
				MarkdownDescription: "Array of Microsoft Teams integration IDs to alert",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the heartbeat monitor",
				MarkdownDescription: "Name of the heartbeat monitor",
			},
			"oncall_alerts": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "IDs of on-call integrations (Grafana, PagerDuty, Opsgenie, Spike)",
				MarkdownDescription: "IDs of on-call integrations (Grafana, PagerDuty, Opsgenie, Spike)",
			},
			"reminder_alert_interval_minutes": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Interval in minutes between reminder alerts (-1 for never)",
				MarkdownDescription: "Interval in minutes between reminder alerts (-1 for never)",
				Validators: []validator.Int64{
					int64validator.AtLeast(-1),
				},
				Default: int64default.StaticInt64(1440),
			},
			"report_period": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Expected interval in seconds between heartbeat pings (for simple schedule)",
				MarkdownDescription: "Expected interval in seconds between heartbeat pings (for simple schedule)",
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"report_period_cron": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Cron expression for expected heartbeat schedule",
				MarkdownDescription: "Cron expression for expected heartbeat schedule",
			},
			"slack_alerts": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Array of Slack integration IDs to alert",
				MarkdownDescription: "Array of Slack integration IDs to alert",
			},
			"timezone": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Timezone for cron schedule",
				MarkdownDescription: "Timezone for cron schedule",
			},
			"user_alerts": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Array of user IDs to alert",
				MarkdownDescription: "Array of user IDs to alert",
			},
			"webhook_alerts": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "IDs of webhooks to associate with this heartbeat",
				MarkdownDescription: "IDs of webhooks to associate with this heartbeat",
			},
		},
	}
}

type HeartbeatModel struct {
	AlertPriority                types.String `tfsdk:"alert_priority"`
	DiscordAlerts                types.List   `tfsdk:"discord_alerts"`
	GracePeriod                  types.Int64  `tfsdk:"grace_period"`
	Id                           types.String `tfsdk:"id"`
	IncidentIoAlerts             types.List   `tfsdk:"incident_io_alerts"`
	MicrosoftTeamsAlerts         types.List   `tfsdk:"microsoft_teams_alerts"`
	Name                         types.String `tfsdk:"name"`
	OncallAlerts                 types.List   `tfsdk:"oncall_alerts"`
	ReminderAlertIntervalMinutes types.Int64  `tfsdk:"reminder_alert_interval_minutes"`
	ReportPeriod                 types.Int64  `tfsdk:"report_period"`
	ReportPeriodCron             types.String `tfsdk:"report_period_cron"`
	SlackAlerts                  types.List   `tfsdk:"slack_alerts"`
	Timezone                     types.String `tfsdk:"timezone"`
	UserAlerts                   types.List   `tfsdk:"user_alerts"`
	WebhookAlerts                types.List   `tfsdk:"webhook_alerts"`
}
