// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_maintenance_window

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func MaintenanceWindowResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"checks": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Array of uptime check IDs to associate with this maintenance window",
				MarkdownDescription: "Array of uptime check IDs to associate with this maintenance window",
			},
			"days_of_week": schema.ListAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "Days of the week when the maintenance window is active",
				MarkdownDescription: "Days of the week when the maintenance window is active",
				Validators: []validator.List{
					listvalidator.SizeAtLeast(1),
				},
			},
			"duration_minutes": schema.Int64Attribute{
				Required:            true,
				Description:         "Duration of the maintenance window in minutes",
				MarkdownDescription: "Duration of the maintenance window in minutes",
			},
			"heartbeats": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Array of heartbeat IDs to associate with this maintenance window",
				MarkdownDescription: "Array of heartbeat IDs to associate with this maintenance window",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Maintenance Window ID",
				MarkdownDescription: "Maintenance Window ID",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(8),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the maintenance window",
				MarkdownDescription: "Name of the maintenance window",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"start_date": schema.StringAttribute{
				Required:            true,
				Description:         "Start time of the maintenance window (HH:MM format)",
				MarkdownDescription: "Start time of the maintenance window (HH:MM format)",
			},
			"timezone": schema.StringAttribute{
				Required:            true,
				Description:         "Timezone for the maintenance window",
				MarkdownDescription: "Timezone for the maintenance window",
			},
		},
	}
}

type MaintenanceWindowModel struct {
	Checks          types.List   `tfsdk:"checks"`
	DaysOfWeek      types.List   `tfsdk:"days_of_week"`
	DurationMinutes types.Int64  `tfsdk:"duration_minutes"`
	Heartbeats      types.List   `tfsdk:"heartbeats"`
	Id              types.String `tfsdk:"id"`
	Name            types.String `tfsdk:"name"`
	StartDate       types.String `tfsdk:"start_date"`
	Timezone        types.String `tfsdk:"timezone"`
}
